[package]
name = "last-algo-course"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "last-algo-course"
path = "src/rust/main.rs"

[dependencies]
